### ISSUE TITLE
2 errors in november 2020

### ISSUE THREAD

**Issue by Madriix** [toc-irc/jbnc#39]
2 errors detected in November 2020 on the current Jbnc version

Error 1:
TypeError: Cannot read property 'indexOf' of undefined
    at TLSSocket.<anonymous> (/home/debian/node/jbnc/bouncer.js:1007:90)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)

Line 1007 : https://github.com/toc-irc/jbnc/blob/master/bouncer.js#L1007
                                  `if(_mode_target[_mode_count]!=this.nick && curchan.aov.indexOf(_this_target)<0 && this.opmode) {`

Errror 2 : 
Another error on line 982
TypeError: Cannot read property 'indexOf' of undefined
    at TLSSocket.<anonymous> (/home/debian/node/jbnc/bouncer.js:982:90)

Line 982 : https://github.com/toc-irc/jbnc/blob/master/bouncer.js#L982
                                 `if(_mode_target[_mode_count]!=this.nick && curchan.aop.indexOf(_this_target)<0 && this.opmode) {`

I don't even know how to fix it actually

**Comment by realrasengan** [comment]
https://github.com/toc-irc/jbnc/commit/29bcf544636bf8b6eae151bf6a51fe4f27a2cf2a

**Comment by Madriix** [comment]
I will test from tomorrow in prod, thank you
